name: Auto Semantic Release

on:
  push:
    branches:
      - master
      
permissions:
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'  # Skip bot commits to avoid loops

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          # Get the latest Git tag, default to v0.0.0 if none exists
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest tag: $LATEST_TAG"

      - name: Bump version (patch)
        id: bump
        run: |
          TAG=${{ env.LATEST_TAG }}
          # Extract major, minor, patch
          MAJOR=$(echo $TAG | cut -d. -f1 | tr -d 'v')
          MINOR=$(echo $TAG | cut -d. -f2)
          PATCH=$(echo $TAG | cut -d. -f3)

          # Increment patch
          PATCH=$((PATCH + 1))

          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New version: $NEW_VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: Release ${{ env.NEW_VERSION }}
          body: "Automated semantic release from commit $GITHUB_SHA"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version badge
        run: |
          BADGE_URL="https://img.shields.io/badge/version-${{ env.NEW_VERSION }}-orange"
          README_FILE="README.md"

          if grep -q "version-" $README_FILE; then
            sed -i "s|!\[version\].*|![version]($BADGE_URL)|" $README_FILE
          else
            # Insert badge at the top of README
            sed -i "1i![version]($BADGE_URL)" $README_FILE
          fi

          git add $README_FILE
          git commit -m "Update version badge to ${{ env.NEW_VERSION }}" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
